from typing import Dict, List, Any

def format_comment_body(finding: Dict[str, Any]) -> str:
    """
    Formats a single finding dict into a rich markdown string suitable for inline PR comments.
    """
    severity = finding.get("severity", "Medium")
    category = finding.get("category", "General")
    issue = finding.get("issue", "")
    suggestion = finding.get("suggestion", "")

    # Severity emoji mapping
    severity_emojis = {
        "High": "🔴 **High**",
        "Medium": "🟡 **Medium**",
        "Low": "🔵 **Low**",
    }
    
    emoji = severity_emojis.get(severity, "🟡 **Medium**")

    # Format the comment body with clear visual styling and details
    body = (
        f"### 🤖 Gemini AI Code Review Finding\n\n"
        f"| Detail | Description |\n"
        f"| :--- | :--- |\n"
        f"| **Severity** | {emoji} |\n"
        f"| **Category** | `{category}` |\n"
        f"| **Issue** | {issue} |\n\n"
        f"#### 💡 Suggestion\n"
        f"{suggestion}\n\n"
        f"---"
    )
    return body

def format_review_summary(findings: List[Dict[str, Any]], total_files_reviewed: int) -> str:
    """
    Formats the list of all findings into a high-level markdown summary for the PR review body.
    """
    total_findings = len(findings)
    
    # Calculate counts by severity
    high_count = sum(1 for f in findings if f.get("severity") == "High")
    medium_count = sum(1 for f in findings if f.get("severity") == "Medium")
    low_count = sum(1 for f in findings if f.get("severity") == "Low")

    # Group findings by file for summary list
    files_with_issues = set(f.get("file") for f in findings if f.get("file"))
    
    if total_findings == 0:
        summary = (
            f"## 🤖 Gemini AI Code Review\n\n"
            f"### 🎉 LGTM! No issues found.\n\n"
            f"I reviewed **{total_files_reviewed}** C# files changed in this PR and found no major violations of SOLID principles, null handling issues, or async/await antipatterns. Excellent work!\n\n"
            f"*Disclaimer: This review was automatically generated by Google Gemini AI.*"
        )
        return summary

    summary = (
        f"## 🤖 Gemini AI Code Review Summary\n\n"
        f"I reviewed **{total_files_reviewed}** changed C# files and found **{total_findings}** code quality findings:\n\n"
        f"- 🔴 **High Severity:** {high_count}\n"
        f"- 🟡 **Medium Severity:** {medium_count}\n"
        f"- 🔵 **Low Severity:** {low_count}\n\n"
        f"### 📁 Files with Findings\n"
    )

    for file in sorted(files_with_issues):
        file_findings = [f for f in findings if f.get("file") == file]
        summary += f"- `{file}` ({len(file_findings)} findings)\n"
        
    summary += (
        f"\n### 📝 Next Steps\n"
        f"Please review the inline comments left on the changed lines and apply the recommended suggestions. "
        f"Once addressed, push the updates to resolve the review.\n\n"
        f"*Disclaimer: This review was automatically generated by Google Gemini AI. Please check all findings manually before merging.*"
    )
    return summary
